package parquet

import (
	"sort"

	"github.com/segmentio/parquet/encoding"
	"github.com/segmentio/parquet/encoding/bytestreamsplit"
	"github.com/segmentio/parquet/encoding/delta"
	"github.com/segmentio/parquet/encoding/dict"
	"github.com/segmentio/parquet/encoding/plain"
	"github.com/segmentio/parquet/encoding/rle"
	"github.com/segmentio/parquet/format"
)

var (
	// Plain is the default parquet encoding.
	Plain plain.Encoding

	// RLE is the hybrid bit-pack/run-length parquet encoding.
	RLE rle.Encoding

	// Dict is the dictionary parquet encoding.
	//
	// This package declares only the RLE_DICTIONARY because using
	// PLAIN_DICTIONARY is now deprecated in Parquet 2.0. However,
	// it is capable of reading file generated by older parquet
	// writers which used the PLAIN_DICTIONARY encoding.
	Dict dict.Encoding

	// DeltaBinaryPacked is the delta binary packed parquet encoding.
	DeltaBinaryPacked delta.BinaryPackedEncoding

	// ByteStreamSplit is an encoding for floating-point data.
	ByteStreamSplit bytestreamsplit.Encoding

	// Table indexing the encodings supported by this package.
	encodings = [...]encoding.Encoding{
		format.Plain:             &Plain,
		format.PlainDictionary:   Dict.PlainEncoding(),
		format.RLE:               &RLE,
		format.RLEDictionary:     &Dict,
		format.DeltaBinaryPacked: &DeltaBinaryPacked,
		format.ByteStreamSplit:   &ByteStreamSplit,
	}
)

func lookupEncoding(enc format.Encoding) encoding.Encoding {
	if enc >= 0 && int(enc) < len(encodings) {
		if e := encodings[enc]; e != nil {
			return e
		}
	}
	return encoding.NotSupported{}
}

func sortEncodings(encodings []encoding.Encoding) {
	if len(encodings) > 1 {
		sort.Slice(encodings, func(i, j int) bool {
			return encodings[i].Encoding() < encodings[j].Encoding()
		})
	}
}

func dedupeSortedEncodings(encodings []encoding.Encoding) []encoding.Encoding {
	if len(encodings) > 1 {
		i := 0

		for _, c := range encodings[1:] {
			if c.Encoding() != encodings[i].Encoding() {
				i++
				encodings[i] = c
			}
		}

		encodings = encodings[:i+1]
	}
	return encodings
}
